apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "formserver.fullname" . }}
  labels:
    {{- include "formserver.labels" . | nindent 4 }}
data:
  resources: {{ toYaml .Values.tomcat.resources | indent 2 }}
  logging.properties: {{ toYaml .Values.tomcat.resources | indent 2 }}
