{{- if .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "formserver.fullname" . }}
  labels:
    release: monitoring
spec:
  endpoints:
    - interval: 10s
      path: /metrics/
      port: http
  namespaceSelector:
    matchNames:
      - {{ include "formserver.fullname" . }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "formserver.fullname" . }}
{{- end }}
